service: amaysim-apigw-example
plugins:
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  stage: ${env:ENV}

functions:
  greet:
    handler: src/handler.greet
    events:
      - http:
          path: greet
          method: get